name: Mend Scan
run-name: 'Mend scan for ${{ github.ref_name }}'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

env:
  PUPPET_AUTH_TOKEN: ${{ secrets.PUPPET_AUTH_TOKEN }}
  BUNDLE_RUBYGEMS___PUPPETCORE__PUPPET__COM: "forge-key:${{ secrets.PUPPET_AUTH_TOKEN }}"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Generate Gemfile.lock
        run: bundle lock

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Mend unified agent
        run: curl -o wss-unified-agent.jar https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar

      - name: Run Mend scan
        run: java -jar wss-unified-agent.jar
        env:
          WS_FILESYSTEMSCAN: false
          WS_CHECKPOLICIES: true
          WS_FORCEUPDATE: true
          WS_APIKEY: ${{ secrets.MEND_API_KEY }}
          WS_USERKEY: ${{ secrets.MEND_TOKEN }}
          WS_WSS_URL: https://saas-eu.whitesourcesoftware.com/agent
          WS_PRODUCTNAME: SCE
          WS_PROJECTNAME: ${{ github.event.repository.name }}
